name: Build App windows

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: [self-hosted, Windows]

    steps:
      # Move to your actual Megacity folder
      - name: Go to Megacity project
        run: |
          cd /mnt/c/Users/ibuser/Documents/UnityProject/megacity-metro  
          git fetch origin
          # git reset --hard origin/main

      # Clean previous build
      - name: Clean build folder
        run: |
          cd /mnt/c/Users/ibuser/Documents/UnityProject/megacity-metro
          rm -rf build || true

      # Run Unity build
      - name: Run Unity Build
        run: |
          cd /mnt/c/Users/ibuser/Documents/UnityProject/megacity-metro

          "/mnt/c/Program Files/Unity/Hub/Editor/2022.3.34f1/Editor/Unity.exe" \
            -batchmode -nographics -quit \
            -projectPath . \
            -buildTarget Win64 \
            -job-worker-count 24 \
            -executeMethod BuildApp.Build \
            -logFile build.log

      # Show log (very useful)
      - name: Show log
        if: always()
        run: |
          cd /mnt/c/Users/ibuser/Documents/UnityProject/megacity-metro
          cat build.log || true

      # Verify output
      - name: Show build result
        run: |
          cd /mnt/c/Users/ibuser/Documents/UnityProject/megacity-metro
          ls -la build || true
