name: Build App windows

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: [self-hosted, Windows]

    steps:
      # Move to your actual Megacity folder
      - name: Go to Megacity project
        run: |
          Set-Location "C:\Users\ibuser\Documents\UnityProject\megacity-metro"
          git fetch origin
          # git reset --hard origin/main

      # Clean previous build
      - name: Clean build folder
        run: |
          Set-Location "C:\Users\ibuser\Documents\UnityProject\megacity-metro"
          $projectPath = "C:\Users\ibuser\Documents\UnityProject\megacity-metro"
          $buildPath = Join-Path $projectPath "build"  
          if (Test-Path $buildPath) {
              Remove-Item $buildPath -Recurse -Force
          }

      # Build
      - name: Run Unity Build
        run: |
          $projectPath = "C:\Users\ibuser\Documents\UnityProject\megacity-metro"
          $unityPath = "C:\Program Files\Unity\Hub\Editor\2022.3.34f1\Editor\Unity.exe"

          Set-Location $projectPath

          & "$unityPath" `
            -batchmode -nographics -quit `
            -projectPath . `
            -buildTarget Win64 `
            -job-worker-count 24 `
            -executeMethod BuildApp.Build `
            -logFile build.log

      # Show log (very useful)
      - name: Show log
        if: always()
        run: |
          $logPath = "C:\Users\ibuser\Documents\UnityProject\megacity-metro\build.log"

          if (Test-Path $logPath) {
              Get-Content $logPath
          } else {
              Write-Output "No log file found"
          }

      # Verify output
      - name: Show build result
        run: |
          $buildPath = "C:\Users\ibuser\Documents\UnityProject\megacity-metro\build"

          if (Test-Path $buildPath) {
              Get-ChildItem -Recurse $buildPath
          } else {
              Write-Output "Build folder not found"
          }
