name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Print machine info
        shell: powershell
        run: |
          Write-Host "Runner is working"
          hostname
          systeminfo

      - name: Check disk
        shell: powershell
        run: |
          Get-PSDrive -PSProvider FileSystem